HTML/CSS & JavaScript capstone project
alphym/Capstone.github.io pull request #1
Opened 2023-02-17 20:40 UTC by alphym

<h3>HTML/CSS & JavaScript capstone project </h3>
-  I personalized the content of my page. Choosed a topic that is a Techgirl meetup .

- I builded only these 2 pages:

- The home page.
- The about page.
- Each of these pages  have versions for 2 different screen sizes:

- Mobile: up to 768px wide.
- Desktop: 768px or wider.
- Interactions

- Links
- The home page  have a link in the menu to the about page.
- The logo in the header links to the home page.
- Mobile menu
- When the user clicks (or taps) the hamburger button on the header, the mobile menu appears over the page.

- The mobile menu  have a close (X) button that closes the menu.
- Dynamic page

- The section "Featured speakers" is created dynamically in JavaScript.

2023-02-17 23:16 UTC, GedeonTS requested changes
# STATUS: CHANGES REQUIRED :recycle: :

Hi @alphym , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif">

## Highlights :tophat:  :+1: 
- No linter errors :+1: 
- Good use of GitHub flow :+1: 
- Amazingly responsive design :clap: 
## Required Changes ♻️
- [ ] Good job on recording a descriptive video for the project :clap:  However, :sob: : you forgot to show us a piece of code that you liked the most, kindly to meet that requirement :recycle: 
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-17 23:16 UTC, GedeonTS commented on about.html
> +            <h2 class="header-title">GIRLS IN TECH MEETUP 2023</h2>
- [x] In order to respect the code semantic HTML rules, I suggest using h2 only if you already have h1 on the page, Kindly fix it as I don't see it before :recycle:

2023-02-17 23:16 UTC, GedeonTS commented on style.css
> +    /* background-color: white; */
- [  ] Kindly make sure to remove all commented-out lines of code to make your code cleaner :recycle:

2023-02-17 23:16 UTC, GedeonTS commented on style.css
> +    /* background-color: #f45917; */
- [x] Kindly remove this line too in order to make your code cleaner :recycle:

2023-02-17 23:16 UTC, GedeonTS commented on script.js
> +            </div>`;
- [x] Kindly make sure this section looks like the Behance design, below are some hints:
  - Adding the grey chess
![Screenshot from 2023-02-18 00-40-11](https://user-images.githubusercontent.com/97834160/219813069-62245bf9-73dc-4f28-af4a-b5f2588e4118.png)

  - removing the border

2023-02-17 23:16 UTC, GedeonTS commented on style.css
> +  /* padding: 0; */
- [ ] Kindly make sure to delete this line too and all other commented-out lines of code to make your code clean :recycle: :

2023-02-17 23:16 UTC, GedeonTS commented on index.html
> +    </footer>
- [ ] Kindly make sure this section doesn't appear on the mobile version as it is on Cindy's design.

![Screenshot from 2023-02-18 01-02-17](https://user-images.githubusercontent.com/97834160/219813615-942b0260-f21a-410b-8a47-b09e3bf67679.png)

2023-02-17 23:16 UTC, GedeonTS commented on index.html
> +            <h1 class="header-title">GIRLS IN TECH MEETUP 2023</h1>
- [ ] Kindly make sure to increase your font size and use the right color for this title as it is on Cindy's design :recycle: 

- Your design :
![Screenshot from 2023-02-18 01-04-01](https://user-images.githubusercontent.com/97834160/219813771-5c509624-e784-434a-80b6-05c3c934b042.png)

- Behance:
![Screenshot from 2023-02-18 01-06-49](https://user-images.githubusercontent.com/97834160/219814101-7603e712-0ede-4482-88c2-e7860c89d175.png)

2023-02-17 23:16 UTC, GedeonTS commented on index.html
> +            </ul>
- [ ] Kindly make the background of your headline and the header are the same to stick to Cindy's design

![Screenshot from 2023-02-18 01-11-41](https://user-images.githubusercontent.com/97834160/219814602-3352e7a1-1022-4492-b30a-fc32ec8c3b83.png)

2023-02-18 22:01 UTC, m05e5 approved these changes
**Hi @alphym 
You did great. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![CleverScornfulBuffalo-size_restricted](https://user-images.githubusercontent.com/37901469/208869296-5ca9f6cc-a1b5-48fd-bd59-78fd83b35471.gif)

## Highlights

✔️ Nice UI
✔️ No linters error

## Optional suggestions



_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**m05e5**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._**

2023-02-18 22:04 UTC, merged